### ISSUE TITLE
Only works for SSSP

### ISSUE THREAD

**Issue by sampollard** [tudelft-atlarge/graphalytics-platforms-graphmat#15]
I have been able to get this platform working but the benchmark stops at SSSP even when
```benchmark.run.algorithms =``` is left blank.

**Comment by mihaic** [comment]
Current development is happening in the `dataformat-granula-distr` branch. We are adapting the code to the latest GraphMat (https://github.com/narayanan2004/GraphMat/tree/distributed_primitives_integration) and Graphalytics (https://github.com/ldbc/ldbc_graphalytics/tree/dataformat-granula) APIs. However, the code is not yet stable; we hope to have a release in the next couple of weeks. Unfortunately, we do not have the resources to address issues in the older code in the `master` branch.

**Comment by sampollard** [comment]
Thank you for the update. Would it be possible to either leave this issue open or update the README so future users can be aware of this?
